spring:
  config:
    activate:
  application:
    name: api

  datasource:
      on-profile: prod
    url: ENC(vK3ggYCmRnJlODS6cbBXJAi+7Mw7qpO3mKVnWz9PV+Mi+aQrVJBY++5ecNXwrnQxgbCgoivoVVDJjDe554GHnyoj8f2rUbkyNbgN/QmNAZa+Cc+Gp1x7huLrQD7BCeLC)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Oywg8yRSKPs0TXgE6rbNaA==)
    password: ENC(R6oW03mOpylO0Fj2BJzvOeMuCiLGT568)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  eureka:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://52.78.155.253:8761/eureka

  server:
    port: 9000